Repository onflow/hybrid-custody, pull requests merged in 2023-08, with the labels that each got.

#141 fix: factory setup transactions
  transactions/dev-setup/setup_nft_filter_and_factory_manager.cdc
  transactions/factory/setup.cdc
Labels: bug

#142 Consolidate OwnedAccount setup txn & comment updates
  contracts/HybridCustody.cdc
  test/HybridCustody_tests.cdc
  transactions/hybrid-custody/setup_owned_account.cdc
  transactions/hybrid-custody/setup_owned_account_and_publish_to_parent.cdc
  transactions/hybrid-custody/setup_owned_account_with_display.cdc
  transactions/hybrid-custody/setup_owned_account_with_display_and_publish_to_parent.cdc
Labels: enhancement

#144 Mainnet deployment details
  README.md
  flow.json
  transactions/factory/setup_nft_ft_manager.cdc
  transactions/factory/setup_nft_manager.cdc
Labels: enhancement

#150 Add badges in `README` for integration tests and code coverage
  README.md
Labels: documentation, enhancement
